version: '3.6'

services:

  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - type: volume
        source: matomo-app
        target: /matomo
      - type: bind
        source: ./matomo_nginx.conf
        target: /etc/nginx/conf.d/default.conf 
    networks:
      - matomo-network
    depends_on:
      - matomo_database
      - matomo

  matomo:
    image: luongbui/matomo:3.5.1
    volumes:
      - type: volume
        source: matomo-app
        target: /matomo 
    networks:
      - matomo-network
    depends_on:
      - matomo_database

  matomo_database:
    image: mysql:5.7.22
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: matomo_db
      MYSQL_USER: matomo
      MYSQL_PASSWORD: matomo
    volumes:
      - type: volume
        source: matomo-database
        target: /var/lib/mysql 
    networks:
      - matomo-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: matomo_database
      PMA_PORT: 3306
    ports:
      - '9090:80'
    networks:
      - matomo-network 
    depends_on:
      - matomo_database
      - matomo

  matomo_database:
    image: mysql:5.7.22
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: matomo_db
      MYSQL_USER: matomo
      MYSQL_PASSWORD: matomo
    volumes:
      - type: volume
        source: matomo-database
        target: /var/lib/mysql 
    networks:
      - matomo-network

networks:
  matomo-network:
    driver: bridge

volumes:
  matomo-app:
  matomo-database:

